// Peatix web scraping service for Singapore events
export async function fetchEventbriteEvents({
  location = 'Singapore',
  categories = '',
  page = 1,
  pageSize = 20,
} = {}) {
  try {
    console.log('Fetching events from Peatix for Singapore...');
    
    // Simulate fetching events from Peatix
    // In a real implementation, this would use a web scraping library
    const mockPeatixEvents = [
      {
        id: '1',
        title: 'Tech Conference 2025',
        date: '2025-07-15',
        time: '09:00',
        location: 'Marina Bay Sands, Singapore',
        description: 'Join us for the biggest tech conference in Singapore featuring industry leaders and innovative startups.',
        category: 'Technology',
        budget: 'High',
        image: 'https://picsum.photos/300/200?random=1',
        latitude: 1.2838,
        longitude: 103.8591,
        color: '#007AFF',
      },
      {
        id: '2',
        title: 'Food & Wine Festival',
        date: '2025-07-15',
        time: '09:00',
        location: 'Gardens by the Bay, Singapore',
        description: 'Experience the finest cuisines and wines from around the world in this spectacular festival.',
        category: 'Food & Drink',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=2',
        latitude: 1.2819,
        longitude: 103.8636,
        color: '#FF6B35',
      },
      {
        id: '3',
        title: 'Startup Networking Night',
        date: '2025-07-25',
        time: '19:00',
        location: 'WeWork, Raffles Place, Singapore',
        description: 'Connect with fellow entrepreneurs and investors in Singapore\'s vibrant startup ecosystem.',
        category: 'Business',
        budget: 'Low',
        image: 'https://picsum.photos/300/200?random=3',
        latitude: 1.2841,
        longitude: 103.8515,
        color: '#34C759',
      },
      {
        id: '4',
        title: 'Jazz in the Park',
        date: '2025-07-30',
        time: '20:00',
        location: 'Botanic Gardens, Singapore',
        description: 'Enjoy an evening of smooth jazz music under the stars in Singapore\'s beautiful Botanic Gardens.',
        category: 'Music',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=4',
        latitude: 1.3151,
        longitude: 103.8162,
        color: '#AF52DE',
      },
      {
        id: '5',
        title: 'Art Exhibition Opening',
        date: '2025-08-05',
        time: '18:30',
        location: 'National Gallery Singapore',
        description: 'Be among the first to view this groundbreaking contemporary art exhibition featuring local and international artists.',
        category: 'Arts',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=5',
        latitude: 1.2905,
        longitude: 103.8520,
        color: '#FF9500',
      },
      {
        id: '6',
        title: 'Fitness Bootcamp',
        date: '2025-08-10',
        time: '07:00',
        location: 'East Coast Park, Singapore',
        description: 'Start your day with an intense fitness bootcamp by the beach. All fitness levels welcome!',
        category: 'Sports',
        budget: 'Low',
        image: 'https://picsum.photos/300/200?random=6',
        latitude: 1.3028,
        longitude: 103.9123,
        color: '#FF3B30',
      },
      {
        id: '7',
        title: 'Coding Workshop',
        date: '2025-08-15',
        time: '14:00',
        location: 'General Assembly, Singapore',
        description: 'Learn the fundamentals of web development in this hands-on coding workshop for beginners.',
        category: 'Education',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=7',
        latitude: 1.2841,
        longitude: 103.8515,
        color: '#5856D6',
      },
      {
        id: '8',
        title: 'Craft Beer Tasting',
        date: '2025-08-20',
        time: '19:30',
        location: 'Brewerkz, Clarke Quay, Singapore',
        description: 'Sample the finest craft beers from Singapore and around the world in this exclusive tasting event.',
        category: 'Food & Drink',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=8',
        latitude: 1.2905,
        longitude: 103.8460,
        color: '#8E8E93',
      },
      // 12 more events
      {
        id: '9',
        title: 'Marathon 2025',
        date: '2025-08-22',
        time: '06:00',
        location: 'Singapore Sports Hub',
        description: 'Join the annual marathon and run with thousands across the city.',
        category: 'Sports',
        budget: 'Low',
        image: 'https://picsum.photos/300/200?random=9',
        latitude: 1.3048,
        longitude: 103.8747,
        color: '#FF9500',
      },
      {
        id: '10',
        title: 'Startup Pitch Night',
        date: '2025-08-25',
        time: '18:00',
        location: 'Block71, Ayer Rajah',
        description: 'Watch startups pitch their ideas to investors.',
        category: 'Business',
        budget: 'Free',
        image: 'https://picsum.photos/300/200?random=10',
        latitude: 1.2992,
        longitude: 103.7876,
        color: '#007AFF',
      },
      {
        id: '11',
        title: 'Vegan Food Fair',
        date: '2025-08-28',
        time: '12:00',
        location: 'Suntec City',
        description: 'Taste the best vegan food from local and international chefs.',
        category: 'Food & Drink',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=11',
        latitude: 1.2931,
        longitude: 103.8572,
        color: '#34C759',
      },
      {
        id: '12',
        title: 'Book Launch: Singapore Stories',
        date: '2025-09-01',
        time: '17:00',
        location: 'Kinokuniya, Orchard',
        description: 'Meet the authors and get your book signed.',
        category: 'Arts',
        budget: 'Low',
        image: 'https://picsum.photos/300/200?random=12',
        latitude: 1.3040,
        longitude: 103.8318,
        color: '#AF52DE',
      },
      {
        id: '13',
        title: 'Yoga in the Park',
        date: '2025-09-05',
        time: '08:00',
        location: 'Fort Canning Park',
        description: 'Start your morning with a relaxing yoga session.',
        category: 'Health',
        budget: 'Low',
        image: 'https://picsum.photos/300/200?random=13',
        latitude: 1.2976,
        longitude: 103.8452,
        color: '#FF3B30',
      },
      {
        id: '14',
        title: 'Film Festival Opening',
        date: '2025-09-10',
        time: '19:00',
        location: 'The Projector',
        description: 'Watch the best indie films from around the world.',
        category: 'Film',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=14',
        latitude: 1.2996,
        longitude: 103.8584,
        color: '#5856D6',
      },
      {
        id: '15',
        title: 'Charity Gala Dinner',
        date: '2025-09-15',
        time: '20:00',
        location: 'Raffles Hotel',
        description: 'Support a good cause at this black-tie event.',
        category: 'Charity',
        budget: 'High',
        image: 'https://picsum.photos/300/200?random=15',
        latitude: 1.2941,
        longitude: 103.8526,
        color: '#FF9500',
      },
      {
        id: '16',
        title: 'Makers Market',
        date: '2025-09-20',
        time: '10:00',
        location: 'Esplanade',
        description: 'Shop for handmade crafts and goods.',
        category: 'Market',
        budget: 'Free',
        image: 'https://picsum.photos/300/200?random=16',
        latitude: 1.2894,
        longitude: 103.8554,
        color: '#34C759',
      },
      {
        id: '17',
        title: 'Photography Walk',
        date: '2025-09-25',
        time: '16:00',
        location: 'Chinatown',
        description: 'Capture the sights of Chinatown with a pro photographer.',
        category: 'Photography',
        budget: 'Low',
        image: 'https://picsum.photos/300/200?random=17',
        latitude: 1.2842,
        longitude: 103.8436,
        color: '#007AFF',
      },
      {
        id: '18',
        title: 'Street Art Tour',
        date: '2025-09-28',
        time: '15:00',
        location: 'Little India',
        description: 'Explore the vibrant street art of Little India.',
        category: 'Art',
        budget: 'Free',
        image: 'https://picsum.photos/300/200?random=18',
        latitude: 1.3066,
        longitude: 103.8496,
        color: '#AF52DE',
      },
      {
        id: '19',
        title: 'Classical Music Night',
        date: '2025-10-01',
        time: '19:30',
        location: 'Victoria Concert Hall',
        description: 'Enjoy an evening of classical music.',
        category: 'Music',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=19',
        latitude: 1.2899,
        longitude: 103.8517,
        color: '#FF6B35',
      },
      {
        id: '20',
        title: 'Halloween Costume Party',
        date: '2025-10-31',
        time: '21:00',
        location: 'Clarke Quay',
        description: 'Dress up and party all night for Halloween!',
        category: 'Party',
        budget: 'Medium',
        image: 'https://picsum.photos/300/200?random=20',
        latitude: 1.2906,
        longitude: 103.8462,
        color: '#FF3B30',
      },
    ];

    // Filter events based on search criteria
    let filteredEvents = mockPeatixEvents;
    
    if (categories) {
      filteredEvents = filteredEvents.filter(event => 
        event.category.toLowerCase().includes(categories.toLowerCase())
      );
    }

    // Simulate pagination
    const startIndex = (page - 1) * pageSize;
    const endIndex = startIndex + pageSize;
    const paginatedEvents = filteredEvents.slice(startIndex, endIndex);

    console.log(`Found ${paginatedEvents.length} events from Peatix`);
    
    return paginatedEvents;
    
  } catch (error) {
    console.error('Error fetching events from Peatix:', error);
    throw new Error('Failed to fetch events from Peatix: ' + (error instanceof Error ? error.message : String(error)));
  }
} 